package com.app.Portfolio;

import java.util.*;

import javax.persistence.*;

import com.app.Position.Position;
import com.app.User.User;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * The Portfolio class is an entity that represents a user's investment portfolio.
 * It contains various attributes related to the portfolio, such as its name, description
 * of the investment strategy, total capital, and a list of positions held.
 * This class is mapped to the "user_portfolio" table in the database.
 */
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "portfolioID")
@Entity
@Table(name = "user_portfolio")
public class Portfolio {

    /**
     * The unique identifier for the portfolio. It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Define the generation strategy for the ID
    private int portfolioID;

    /**
     * The user to whom this portfolio belongs. It establishes a many-to-one relationship
     * with the User entity.
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    @JsonBackReference
    private User user;

    /**
     * The name of the portfolio.
     */
    private String portfolioName;

    /**
     * A description of the investment strategy employed for this portfolio.
     */
    private String strategyDesc;

    /**
     * The total capital in USD assigned to this portfolio.
     */
    private float capitalUSD;

    /**
     * A list of positions (investments) included in this portfolio.
     */
    private ArrayList<Position> positions;

    /**
     * Timestamp indicating when this portfolio was created.
     */
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdTimestamp;

    /**
     * Timestamp indicating when this portfolio was last modified.
     */
    @Temporal(TemporalType.TIMESTAMP)
    private Date lastModifiedTimestamp;

    // ------------------ Getters and Setters (Start) ------------------
    public Portfolio() {
    }

    public Portfolio(int portfolioID, User user, String portfolioName, String strategyDesc, float capitalUSD,
            ArrayList<Position> positions) {
        this.portfolioID = portfolioID;
        this.user = user;
        this.portfolioName = portfolioName;
        this.strategyDesc = strategyDesc;
        this.capitalUSD = capitalUSD;
        this.positions = positions;
        this.createdTimestamp = new Date();
        this.lastModifiedTimestamp = new Date();
    }

    public int getPortfolioID() {
        return portfolioID;
    }

    public void setPortfolioID(int portfolioID) {
        this.portfolioID = portfolioID;
    }

    public String getPortfolioName() {
        return portfolioName;
    }

    public void setPortfolioName(String portfolioName) {
        this.portfolioName = portfolioName;
    }

    public String getStrategyDesc() {
        return strategyDesc;
    }

    public void setStrategyDesc(String strategyDesc) {
        this.strategyDesc = strategyDesc;
    }

    public float getCapitalUSD() {
        return capitalUSD;
    }

    public void setCapitalUSD(float capitalUSD) {
        this.capitalUSD = capitalUSD;
    }

    public ArrayList<Position> getPositions() {
        return positions;
    }

    public void setPositions(ArrayList<Position> positions) {
        this.positions = positions;
    }

    // Method to set the user of the portfolio
    public void setUser(User user) {
        this.user = user;
    }

    public User getUser() {
        return user;
    }

    // ------------------- Getters and Setters (End) -------------------

    public Date getCreatedTimestamp() {
        return createdTimestamp;
    }

    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    public Date getLastModifiedTimestamp() {
        return lastModifiedTimestamp;
    }

    public void setLastModifiedTimestamp(Date lastModifiedTimestamp) {
        this.lastModifiedTimestamp = lastModifiedTimestamp;
    }
}